name: fluttergram
description: Fluttergram App.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  google_fonts: ^3.0.1
  responsive_framework: ^0.2.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
