name: fluttergram
description: Fluttergram App.
publish_to: none
version: 2.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  responsive_framework: ^1.4.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/